// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVrsYVcpCRRBgzo8Wp4-3sMV8taRXU94',
    appId: '1:749565086646:web:714b1517b50ff8ffd2cf17',
    messagingSenderId: '749565086646',
    projectId: 'flutter-list-quiz',
    authDomain: 'flutter-list-quiz.firebaseapp.com',
    storageBucket: 'flutter-list-quiz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2hJga33VxDT75oLTT9yrClJcEi2ZFj9w',
    appId: '1:749565086646:android:a6d8da8a08d71b4ad2cf17',
    messagingSenderId: '749565086646',
    projectId: 'flutter-list-quiz',
    storageBucket: 'flutter-list-quiz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq0jXowGaYwegntiC16H5HzoDclGbdFA4',
    appId: '1:749565086646:ios:1a6c4b9bb343ee73d2cf17',
    messagingSenderId: '749565086646',
    projectId: 'flutter-list-quiz',
    storageBucket: 'flutter-list-quiz.appspot.com',
    iosBundleId: 'com.example.flutterList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq0jXowGaYwegntiC16H5HzoDclGbdFA4',
    appId: '1:749565086646:ios:1a6c4b9bb343ee73d2cf17',
    messagingSenderId: '749565086646',
    projectId: 'flutter-list-quiz',
    storageBucket: 'flutter-list-quiz.appspot.com',
    iosBundleId: 'com.example.flutterList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIVrsYVcpCRRBgzo8Wp4-3sMV8taRXU94',
    appId: '1:749565086646:web:f663e4d0cbc2b14cd2cf17',
    messagingSenderId: '749565086646',
    projectId: 'flutter-list-quiz',
    authDomain: 'flutter-list-quiz.firebaseapp.com',
    storageBucket: 'flutter-list-quiz.appspot.com',
  );
}
